version: "3.9"

services:
  db:
    image: postgres:15
    container_name: builder-masa-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: charity_db
    ports:
      - "5441:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - website-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d charity_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  nextjs:
    build: .
    container_name: website-builder
    environment:
      DATABASE_URL: "postgres://49689f5bd1bb99c7adaaf751488678b5a782e333026321443a22a36211397286:sk_RNoanOSKh1oY4ApF_-IkG@db.prisma.io:5432/postgres?sslmode=require"
      NODE_ENV: production
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - website-network

volumes:
  db-data:

networks:
  website-network:
    driver: bridge